### ISSUE TITLE
Support capture groups in route regex

### ISSUE THREAD

**Issue by 0x00002a** [Tectu/malloy#12]
Taken from: #10 

Would be nice if the regex route supported capture groups, maybe passed in as a vector (to the handler function). Currently I'm doing my own parsing of the request's target in order to grab the bits I need from it. Could wrap the version without the extra args in a lambda before storing it or something.

**Comment by 0x00002a** [comment]
I can do this one quite easily building on: #14. Without any needing to wrap it either, have it as a `bool` in the template for `endpoint_regex` and then `std::conditional` on the function type for the handler. As a bonus this means the capture group can be skipped for handlers which don't use it, don't pay for what you don't use and all that.

**Comment by Tectu** [comment]
#14 was merged - wanna create a PR for this?
