### ISSUE TITLE
Type aliases for websocket::connection

### ISSUE THREAD

**Issue by Tectu** [Tectu/malloy#34]
Personally I don't like to see code like this in an application / outside of a library:
```cpp
class my_app
{
private:
    malloy::websocket::connection<false> m_ws;
};
```
It is not immediately clear what this boolean template parameter does without further investigation (or simply knowing it).

I would vote for adding type aliases for client & server connections which are defined as `connection<true>` and `connection<false>` respectively.

@0x00002a any thoughts?

**Comment by 0x00002a** [comment]
@Tectu https://github.com/Tectu/malloy/blob/9eecc9cc9da9ca22d28323fcaec832df9a974ac0/lib/malloy/server/websocket/connection/connection.hpp#L19?

**Comment by Tectu** [comment]
🤦 
Don't hate me 😋
