### ISSUE TITLE
Set agent strings properly

### ISSUE THREAD

**Issue by Tectu** [Tectu/malloy#37]
Currently, agent strings are all over the place. This needs some cleaning up / more consistency.

We want to have something like `malloy-client <version>` and `malloy-server <version>`.

**Comment by 0x00002a** [comment]
Could add it to the config along with #35, have a default and then let the user customise it if they really want

**Comment by Tectu** [comment]
I've been wondering whether there is a scenario where a user might want to have different agent strings for different connections of the same type.
For example, given an HTTP server, would a connection ever need to have a different agent string than other HTTP connections served by the same server?

**Comment by Tectu** [comment]
@0x00002a how busy are you currently? I'd really like to move to the first release ASAP to make maintaining applications consuming this library easier and hopefully also attracting more users & contributors.

Do you feel like giving this a go?

**Comment by 0x00002a** [comment]
Sure, I'll have a crack at it along with #35 tomorrow
