### ISSUE TITLE
websocket::send() default callback

### ISSUE THREAD

**Issue by Tectu** [Tectu/malloy#41]
In my opinion there are plenty of cases where one might want to send something through a websocket but not necessarily care about the callback. Currently, this requires the user to specify an empty callback handler.

@0x00002a what do you think about providing a default callback handler (an empty one) so a user might just do this:
```cpp
conn->send(malloy::buffer("foo"));
```
instead of:
```cpp
conn->send(malloy::buffer("foo"), [](auto, auto){});
```

**Comment by 0x00002a** [comment]
Agreed, that would be better. There does need to be a way to report errors though, I don't like the idea of letting the user easily (potentially accidentially even) ignore them, which I guess is more #40.

**Comment by Tectu** [comment]
I agree. Lets close this down as the future of this will mainly be dictated by the outcome of #40.
