### ISSUE TITLE
WebSocket connection `stop()` naming

### ISSUE THREAD

**Issue by Tectu** [Tectu/malloy#53]
Currently, `websocket::connection()` has the following (relevant for this discussion) functions:
- `make()`
- `connect()`
- `accept()`
- `stop()`
- `read()`
- `send()`

I would like to argue that `stop()` is not really fitting in this scheme. Personally I would go with renaming it to `disconnect()` instead.

@0x00002a Any objections?

**Comment by 0x00002a** [comment]
Nope, only reason its `stop` is because I ported the server side of websocket first. Not sure `disconnect` fits great but no objections. `close` might work too. Up to you :p

**Comment by Tectu** [comment]
I'd say lets go with `disconnect()` as that tends to pair well with `connect()` :p
Naming it `close()` would make sense too but then I'd feel the urge to rename `connect()` to `open()` ^^
