### ISSUE TITLE
Splitting log - Separate log for access logging

### ISSUE THREAD

**Issue by Tectu** [Tectu/malloy#77]
I think it's a good idea to split up the log into two separate log interfaces: One for access logging and one for everything else.

Applications consuming 'malloy' will typically have the overall "system logger" for reporting any sort of system relevant information but might still want (or need) logging for access information (eg. logging each request received). Currently everything ends up in the same log file which is rather cumbersome to work with in a larger application.

**Comment by Tectu** [comment]
@0x00002a Shall we get this into `v0.1`? What do you think?

**Comment by 0x00002a** [comment]
I personally don't have a huge amount of use for it currently, so I vote for leaving it for later :p
