### ISSUE TITLE
Split CI into system categories

### ISSUE THREAD

**Issue by Tectu** [Tectu/malloy#83]
Currently there are two GitHub Actions/Workflows: Once general "CI" and one "MSYS2".

Is there a way to have multiple, separate actions for each system while still having one place where we define the various build configurations (matrix) etc?

Personally I'd like to have the following actins/workflows:
- Windows (MSVC, MSYS2)
- Linux (Ubuntu, other distributions, ...)
- BSD (FreeBSD, other distributions, ...)

I understand that this is possible by just having separate files. However, I would like to have all configuration releveant options in one file and then include that in each specific workflow.

@0x00002a would you happen to have any experience on this?

**Comment by 0x00002a** [comment]
Unfortunately I don't know a way this can be done without a file per one. The name of it is defined at the top of the file and is the general name for the workflow. It should be possible to move the msys one into the "CI" file but afaik splitting them would require duplication of configuration, or maybe using a preprocessor to generate them or something equally as nasty

**Comment by Tectu** [comment]
I read through the docs and yeah... :/
I assumed they wouldn't support proper templates but I hoped that one could do by including files containing variables like in a Makefile or similar style.

Well then... Still hoping to at one point get some time to start writing a CI matching my requirements from scratch :)
