### ISSUE TITLE
[Bug] action_queue may execute actions unqueued when starting from empty

### ISSUE THREAD

**Issue by 0x00002a** [Tectu/malloy#87]
This is mostly for tracking, I think I've fixed it but I'm just testing it currently. The issue is that `action_queue` _may_ execute actions unqueued if it is empty when the first action is queued and the first action takes longer to complete than the code to the next push. 

e.g.:

```cpp
auto conn = // websocket::connection<...>
conn->send(...);
conn->send(...); // This may cause an issue as both async_write's get executed at once
```

**Comment by Tectu** [comment]
Wow, this is a nasty one...

We might be able to add some dummy code which performs a long-lasting action which is only used during testing?
