### ISSUE TITLE
Add boost 1.77 to CI

### ISSUE THREAD

**Issue by Tectu** [Tectu/malloy#90]
Boost version `1.77.0` was released recently.
We should probably extend the CI pipeline(s) to also test against this new version.

**Comment by 0x00002a** [comment]
On a related note, iirc 1.77.0 has some improvements to `asio`'s concepts support for msvc and gcc. See: [this](https://github.com/Tectu/malloy/issues/70#issuecomment-890366107) (comment) for some issues I ran into with 1.76

**Comment by Tectu** [comment]
Resolved by @0x00002a in commit c88fe6c5e41b71432af939e92bf086fcf18f5f3e
