### ISSUE TITLE
Endpoint test suite fails to build

### ISSUE THREAD

**Issue by Tectu** [Tectu/malloy#93]
Since commit 9bf5a3ce9ea9ebfc5d082086664bf874c50a148c the `endpoints.cpp` test suite fails to build.

Temporarily disabled in commit 5298388db27b1b42d70fbf7400d3f5d89de57333.

**Comment by Tectu** [comment]
@0x00002a feel free to join back in if you have time & motivation during the holidays :p

**Comment by Tectu** [comment]
The problem boils down to `malloy::http::request` not providing a constructor accepting an HTTP header.

**Comment by 0x00002a** [comment]
Thats... weird. Why didn't it fail to build before is whats confusing me. As far as I can tell from the history, that code should never have compiled in the first place. I'm guessing theres some template that wasn't instantated but again I can't see anything that would cause that in 9bf5a3ce9ea9ebfc5d082086664bf874c50a148c.

**Comment by Tectu** [comment]
> Thats... weird. Why didn't it fail to build before is whats confusing me.

You and me both... :D 
I'm truly perplexed by this one.
